version: '3'
services:
  api:
    build: .
    ports:
      - "8080:8080"
    networks:
      - my_network  # Attach this service to the custom network

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=teste
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    ports:
      - "5432:5432"
    networks:
      - my_network  # Attach this service to the custom network

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - my_network  # Attach this service to the custom network

volumes:
  pgadmin_data:

networks:
  my_network:  # Define the custom network named "my_network"
